In [2]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
# create first tensor with tf.constant()
scalar= tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#number of dimensiosn of the tensor
scalar.ndim

0

In [ ]:
# create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# create a matrix
matrix=tf.constant([[10,7,1,0],[7,10,3,6]])
matrix

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[10,  7,  1,  0],
       [ 7, 10,  3,  6]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix=tf.constant([[10.,7.], [3.,2],[8,9]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#create a tensor
tensor=tf.constant([[[1,2,3],[4,5,6]],
[[7,8,9], [10,11,12]],
[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
tensor1=tf.constant([[1],[2],[3]])
tensor1

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>

In [ ]:
tensor1.ndim

2

In [ ]:
tensor2=tf.constant([[[1,2,3],[3,4,3],[5,6,3],[0,0,3]],
                     [[7,8,3],[9,10,3],[11,12,3],[1,1,3]]])
tensor2

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 3,  4,  3],
        [ 5,  6,  3],
        [ 0,  0,  3]],

       [[ 7,  8,  3],
        [ 9, 10,  3],
        [11, 12,  3],
        [ 1,  1,  3]]], dtype=int32)>

In [ ]:
tensor2.ndim

3

In [ ]:
tensor3=tf.constant([[[1,2,3],[3,4,3],[5,6,3],[0,0,3]],
                     [[1,2,3],[3,4,3],[5,6,3],[0,0,3]],
                     [[1,2,3],[3,4,3],[5,6,3],[0,0,3]],
                     [[1,2,3],[3,4,3],[5,6,3],[0,0,3]],
                     [[7,8,3],[9,10,3],[11,12,3],[1,1,3]]])
tensor3

<tf.Tensor: shape=(5, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 3,  4,  3],
        [ 5,  6,  3],
        [ 0,  0,  3]],

       [[ 1,  2,  3],
        [ 3,  4,  3],
        [ 5,  6,  3],
        [ 0,  0,  3]],

       [[ 1,  2,  3],
        [ 3,  4,  3],
        [ 5,  6,  3],
        [ 0,  0,  3]],

       [[ 1,  2,  3],
        [ 3,  4,  3],
        [ 5,  6,  3],
        [ 0,  0,  3]],

       [[ 7,  8,  3],
        [ 9, 10,  3],
        [11, 12,  3],
        [ 1,  1,  3]]], dtype=int32)>

In [ ]:
tensor3.ndim

3

In [ ]:
tensor4d=tf.constant([
                      [[[1,2,3],[3,4,3],[5,6,3],[0,0,3]],
                      [[1,2,3],[3,4,3],[5,6,3],[0,0,3]],
                      [[1,2,3],[3,4,3],[5,6,3],[0,0,3]],
                      [[1,2,3],[3,4,3],[5,6,3],[0,0,3]],
                      [[7,8,3],[9,10,3],[11,12,3],[1,1,3]]],

                      [[[1,2,3],[3,4,3],[5,6,3],[0,0,3]],
                      [[1,2,3],[3,4,3],[5,6,3],[0,0,3]],
                      [[1,2,3],[3,4,3],[5,6,3],[0,0,3]],
                      [[1,2,3],[3,4,3],[5,6,3],[0,0,3]],
                      [[7,8,3],[9,10,3],[11,12,3],[1,1,3]]]
                    ]
                    )
tensor4d

<tf.Tensor: shape=(2, 5, 4, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 3,  4,  3],
         [ 5,  6,  3],
         [ 0,  0,  3]],

        [[ 1,  2,  3],
         [ 3,  4,  3],
         [ 5,  6,  3],
         [ 0,  0,  3]],

        [[ 1,  2,  3],
         [ 3,  4,  3],
         [ 5,  6,  3],
         [ 0,  0,  3]],

        [[ 1,  2,  3],
         [ 3,  4,  3],
         [ 5,  6,  3],
         [ 0,  0,  3]],

        [[ 7,  8,  3],
         [ 9, 10,  3],
         [11, 12,  3],
         [ 1,  1,  3]]],


       [[[ 1,  2,  3],
         [ 3,  4,  3],
         [ 5,  6,  3],
         [ 0,  0,  3]],

        [[ 1,  2,  3],
         [ 3,  4,  3],
         [ 5,  6,  3],
         [ 0,  0,  3]],

        [[ 1,  2,  3],
         [ 3,  4,  3],
         [ 5,  6,  3],
         [ 0,  0,  3]],

        [[ 1,  2,  3],
         [ 3,  4,  3],
         [ 5,  6,  3],
         [ 0,  0,  3]],

        [[ 7,  8,  3],
         [ 9, 10,  3],
         [11, 12,  3],
         [ 1,  1,  3]]]], dtype

In [ ]:
tensor4d.ndim

4

In [ ]:
tensor5d=tf.constant([[[[[1],[2]],
                        [[1],[3]],
                        [[1],[3]]],

                       [[[1],[2]],
                        [[1],[3]],
                        [[1],[3]]]],

                      [[[[1],[2]],
                        [[1],[3]],
                        [[1],[3]]],

                       [[[1],[2]],
                        [[1],[3]],
                        [[1],[3]]]]])

tensor5d

<tf.Tensor: shape=(2, 2, 3, 2, 1), dtype=int32, numpy=
array([[[[[1],
          [2]],

         [[1],
          [3]],

         [[1],
          [3]]],


        [[[1],
          [2]],

         [[1],
          [3]],

         [[1],
          [3]]]],



       [[[[1],
          [2]],

         [[1],
          [3]],

         [[1],
          [3]]],


        [[[1],
          [2]],

         [[1],
          [3]],

         [[1],
          [3]]]]], dtype=int32)>

In [ ]:
tensor5d.ndim

5

In [4]:
# variables
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([11,7])
changeable_tensor,unchangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([11,  7], dtype=int32)>)

In [5]:
# Use assign()
changeable_tensor[0].assign(6)
changeable_tensor[1].assign(8)

changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([6, 8], dtype=int32)>

In [6]:
# Try change unchaneaglbe tensor
unchangeable_tensor[0].assign(6)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [13]:
# create random tensors

random_tensor1=tf.random.Generator.from_seed(42)   # set seed for reproducibility
random_tensor1= random_tensor1.normal(shape=(3,2))
random_tensor1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [32]:
# create random tensors changing all the time (No Seed)

random_tensor2=tf.random.Generator.from_non_deterministic_state()   # set seed for reproducibility
random_tensor2= random_tensor2.normal(shape=(3,2))
random_tensor2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.03292066,  1.0393177 ],
       [-0.56649524, -0.12137437],
       [ 0.49244252, -1.4064096 ]], dtype=float32)>

In [33]:
# are there equal
random_tensor1== random_tensor2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

In [45]:
# Shuffle the order of elements in a tensor
not_shuffled=tf.constant([[1,2],
                          [3,4],
                          [5,6]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [46]:
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

In [47]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [51]:
tf.random.set_seed(42)   # global seed
tf.random.shuffle(not_shuffled, seed=42 )  # operation seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>