In [1]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [2]:
# create first tensor with tf.constant()
scalar= tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#number of dimensiosn of the tensor
scalar.ndim

0

In [6]:
# create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
vector.ndim

1

In [10]:
# create a matrix
matrix=tf.constant([[10,7,1,0],[7,10,3,6]])
matrix

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[10,  7,  1,  0],
       [ 7, 10,  3,  6]], dtype=int32)>

In [9]:
matrix.ndim

2

In [11]:
another_matrix=tf.constant([[10.,7.], [3.,2],[8,9]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [12]:
another_matrix.ndim

2

In [13]:
#create a tensor
tensor=tf.constant([[[1,2,3],[4,5,6]],
[[7,8,9], [10,11,12]],
[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [14]:
tensor.ndim

3

In [15]:
tensor1=tf.constant([[1],[2],[3]])
tensor1

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>

In [16]:
tensor1.ndim

2

In [20]:
tensor2=tf.constant([[[1,2,3],[3,4,3],[5,6,3],[0,0,3]],
                     [[7,8,3],[9,10,3],[11,12,3],[1,1,3]]])
tensor2

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 3,  4,  3],
        [ 5,  6,  3],
        [ 0,  0,  3]],

       [[ 7,  8,  3],
        [ 9, 10,  3],
        [11, 12,  3],
        [ 1,  1,  3]]], dtype=int32)>

In [21]:
tensor2.ndim

3

In [22]:
tensor3=tf.constant([[[1,2,3],[3,4,3],[5,6,3],[0,0,3]],
                     [[1,2,3],[3,4,3],[5,6,3],[0,0,3]],
                     [[1,2,3],[3,4,3],[5,6,3],[0,0,3]],
                     [[1,2,3],[3,4,3],[5,6,3],[0,0,3]],
                     [[7,8,3],[9,10,3],[11,12,3],[1,1,3]]])
tensor3

<tf.Tensor: shape=(5, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 3,  4,  3],
        [ 5,  6,  3],
        [ 0,  0,  3]],

       [[ 1,  2,  3],
        [ 3,  4,  3],
        [ 5,  6,  3],
        [ 0,  0,  3]],

       [[ 1,  2,  3],
        [ 3,  4,  3],
        [ 5,  6,  3],
        [ 0,  0,  3]],

       [[ 1,  2,  3],
        [ 3,  4,  3],
        [ 5,  6,  3],
        [ 0,  0,  3]],

       [[ 7,  8,  3],
        [ 9, 10,  3],
        [11, 12,  3],
        [ 1,  1,  3]]], dtype=int32)>

In [23]:
tensor3.ndim

3

In [28]:
tensor4d=tf.constant([
                      [[[1,2,3],[3,4,3],[5,6,3],[0,0,3]],
                      [[1,2,3],[3,4,3],[5,6,3],[0,0,3]],
                      [[1,2,3],[3,4,3],[5,6,3],[0,0,3]],
                      [[1,2,3],[3,4,3],[5,6,3],[0,0,3]],
                      [[7,8,3],[9,10,3],[11,12,3],[1,1,3]]],

                      [[[1,2,3],[3,4,3],[5,6,3],[0,0,3]],
                      [[1,2,3],[3,4,3],[5,6,3],[0,0,3]],
                      [[1,2,3],[3,4,3],[5,6,3],[0,0,3]],
                      [[1,2,3],[3,4,3],[5,6,3],[0,0,3]],
                      [[7,8,3],[9,10,3],[11,12,3],[1,1,3]]]
                    ]
                    )
tensor4d

<tf.Tensor: shape=(2, 5, 4, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 3,  4,  3],
         [ 5,  6,  3],
         [ 0,  0,  3]],

        [[ 1,  2,  3],
         [ 3,  4,  3],
         [ 5,  6,  3],
         [ 0,  0,  3]],

        [[ 1,  2,  3],
         [ 3,  4,  3],
         [ 5,  6,  3],
         [ 0,  0,  3]],

        [[ 1,  2,  3],
         [ 3,  4,  3],
         [ 5,  6,  3],
         [ 0,  0,  3]],

        [[ 7,  8,  3],
         [ 9, 10,  3],
         [11, 12,  3],
         [ 1,  1,  3]]],


       [[[ 1,  2,  3],
         [ 3,  4,  3],
         [ 5,  6,  3],
         [ 0,  0,  3]],

        [[ 1,  2,  3],
         [ 3,  4,  3],
         [ 5,  6,  3],
         [ 0,  0,  3]],

        [[ 1,  2,  3],
         [ 3,  4,  3],
         [ 5,  6,  3],
         [ 0,  0,  3]],

        [[ 1,  2,  3],
         [ 3,  4,  3],
         [ 5,  6,  3],
         [ 0,  0,  3]],

        [[ 7,  8,  3],
         [ 9, 10,  3],
         [11, 12,  3],
         [ 1,  1,  3]]]], dtype

In [29]:
tensor4d.ndim

4

In [31]:
tensor5d=tf.constant([[[[[1],[2]],
                        [[1],[3]],
                        [[1],[3]]],

                       [[[1],[2]],
                        [[1],[3]],
                        [[1],[3]]]],

                      [[[[1],[2]],
                        [[1],[3]],
                        [[1],[3]]],

                       [[[1],[2]],
                        [[1],[3]],
                        [[1],[3]]]]])

tensor5d

<tf.Tensor: shape=(2, 2, 3, 2, 1), dtype=int32, numpy=
array([[[[[1],
          [2]],

         [[1],
          [3]],

         [[1],
          [3]]],


        [[[1],
          [2]],

         [[1],
          [3]],

         [[1],
          [3]]]],



       [[[[1],
          [2]],

         [[1],
          [3]],

         [[1],
          [3]]],


        [[[1],
          [2]],

         [[1],
          [3]],

         [[1],
          [3]]]]], dtype=int32)>

In [32]:
tensor5d.ndim

5