<a href="https://colab.research.google.com/github/pascalbuchert/Python-AI/blob/main/00_tensorflow_fundamentals_Part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Matrix Multiplication**
www.matrixmultiplication.xyz


In [80]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [81]:
# matrix multiplication in tensor flow
# create a rank 4 tensor

tensor = tf.zeros(shape=[2,3,4,5])
tensor


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [82]:
a=tf.constant([1,2,3,4,5,6], shape=[2,3])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [84]:
b=tf.constant([7,8,9,10,11,12], shape =[3,2])
b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [85]:
c=tf.matmul(a,b)
c #c= a x b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [89]:
# Matrix multiplication
print(a)
tf.matmul(a,b)
tf.matmul(b,a)


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]], dtype=int32)>

In [90]:
# Tensor definition
tensor=tf.constant([10,7,3,4], shape=[2,2])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [92]:
tensor, tensor


(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>)

In [91]:
tensor * tensor
# Wrong result !!!!

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [93]:
tf.matmul(tensor, tensor)
# Correct Result !!

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [103]:
tensor_a=tf.constant([1,2,5,7,2,1,3,3,3], shape=[3,3])
tensor_a

tensor_b=tf.constant([3,5,6,7,1,8], shape=[3,2])
tensor_b

tensor_a, tensor_b

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [101]:
# tensor_a * tensor_b
# -> ERROR : Incompatible shapes

In [111]:
# tensor multiplication : Use @
tensor_a @ tensor_b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [104]:
#
tf.matmul(tensor_a, tensor_b)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [110]:
tf.matmul(tensor_b, tensor_b)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [115]:
# create a tensor (3,2,)
X = tf.constant([[1,2],[3,4,],[5,6]])
Y = tf.constant([[7,8],
                [9,10],
                 [11,12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [116]:
# Matrix multiplication of matrix same shape
# X @ Y
# ERROR: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name:

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [117]:
# Matrix multiplication of matrix same shape
# tf.matmul(X, Y)
# ERROR: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name:

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [120]:
# Resource
# https://mathsisfun.com/algebra/matrix-multiplying.html

# There are 2 rules on tensors or matrics for multiplication:
# 1, the inner dimension muss match
# 2, the resulting matrix has the shape of the inner dimension
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [124]:
# Reshape Y
Y_Reshaped = tf.reshape(Y, [2,3])
X, Y, Y_Reshaped,  X @ Y_Reshaped

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]], dtype=int32)>)

In [128]:
X.shape,  Y_Reshaped

(TensorShape([3, 2]),
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>)

In [130]:
tf.matmul (X, Y_Reshaped)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [131]:
tf.matmul (Y_Reshaped, X)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 76, 100],
       [103, 136]], dtype=int32)>

In [132]:
tf.matmul(tf.reshape(X, shape=(2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [133]:
tf.reshape(X, shape=(2,3)).shape, Y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [135]:
# Transpose
# do the same a reshape

X, tf.transpose(X), tf.reshape(X, shape=(2,3,))


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [145]:
Toto=tf.constant([1,2,3,4,5,6,7,8], shape= [4,2])
Toto, tf.transpose(Toto), tf.reshape(Toto,[2,4])

(<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]], dtype=int32)>,
 <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[1, 3, 5, 7],
        [2, 4, 6, 8]], dtype=int32)>,
 <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]], dtype=int32)>)

In [157]:
# Transpose Flips the axis
print ("X:", X), Y, print ("Y:", Y) , print ("Transpose X:", tf.transpose(X)) ,print ("Transpose(X) * Y:", tf.matmul(tf.transpose(X),Y))

X: tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Y: tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
Transpose X: tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)
Transpose(X) * Y: tf.Tensor(
[[ 89  98]
 [116 128]], shape=(2, 2), dtype=int32)


(None,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>,
 None,
 None,
 None)