<a href="https://colab.research.google.com/github/pascalbuchert/Python-AI/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cover introduction to tensors

In [1]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [2]:
# create first tensor with tf.constant()
scalar= tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#number of dimensiosn of the tensor
scalar.ndim

0

In [4]:
# create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check dimension of the vector
vector.ndim

1

In [6]:
# create a matrix
matrix=tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

# create another matrix

In [8]:
another_matrix=tf.constant([[10.,7.], [3.,2],[8,9]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
another_matrix_again=tf.constant([[10,7,1], [3,2,11],[8,9,101]],dtype=tf.float16)
another_matrix_again

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[ 10.,   7.,   1.],
       [  3.,   2.,  11.],
       [  8.,   9., 101.]], dtype=float16)>

In [11]:
another_matrix_again.ndim

2

In [12]:
#create a tensor
tensor=tf.constant([[[1,2,3],
 [4,5,6]],
[[7,8,9],
 [10,11,12]],
        [[13,14,15],
                   [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
tensor.ndim

3

In [14]:
# variables
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
changeable_tensor[0] =7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# Use assign()
changeable_tensor[0].assign(6)
changeable_tensor[1].assign(8)

changeable_tensor

In [ ]:
# Try change unchaneaglbe tensor
unchangeable_tensor[0].assign(6)
unchangeable_tensor

In [ ]:
# create random tensors

random_tensor1=tf.random.Generator.from_seed(42)   # set seed for reproducibility
random_tensor1= random_tensor1.normal(shape=(3,2))
random_tensor1

In [ ]:
# normal distribution
random_2=tf.random.Generator.from_seed(42)
random_2= random_2.normal(shape=(3,2))
random_2

In [ ]:
# are there equal
random_tensor1== random_2

In [ ]:
# seed makes it not random

In [ ]:
# Shuffle the order of elements in a tensor
not_shuffled=tf.constant([[10,7],
                          [3,4],
                          [2,5]])
not_shuffled

In [ ]:
not_shuffled.ndim

In [ ]:
not_shuffled=tf.constant([[10,7],
                          [3,4],
                          [2,5]])
tf.random.shuffle(not_shuffled)


In [ ]:
tf.random.shuffle(not_shuffled)

In [ ]:
not_shuffled

In [ ]:
tf.random.set_seed(42)   # global seed
tf.random.shuffle(not_shuffled, seed=42 )  # operation seed

Exercice practice with 5 random tensors and shuffle them
https://www.tensorflow.org/api_docs/python/tf/random/set_seed


In [ ]:
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

In [ ]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

In [ ]:
tf.random.set_seed(1234)

@tf.function
def f():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

@tf.function
def g():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

print(f())  # prints '(A1, A2)'
print(g())  # prints '(A1, A2)'

In [ ]:
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

In [ ]:
@tf.function
def foo():
  a = tf.random.uniform([1], seed=1)
  b = tf.random.uniform([1], seed=1)
  return a, b
print(foo())  # prints '(A1, A1)'
print(foo())  # prints '(A2, A2)'

@tf.function
def bar():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b
print(bar())  # prints '(A1, A2)'
print(bar())  # prints '(A3, A4)'

### Lesson **20**

In [ ]:
not_shuffled=tf.constant([[1,2],
                          [3,4],
                          [5,6]])


In [ ]:
tf.random.shuffle(not_shuffled)

In [ ]:
tf.random.shuffle(not_shuffled, seed=42)



In [ ]:
tf.random.set_seed(40)                    # global random seed
tf.random.shuffle(not_shuffled, seed=40)  # operational random seed


In [ ]:
### other ways to make tensors
# numpy.ones

tf.ones([10,7])

In [ ]:
tf.zeros(shape=(3,4))

In [ ]:
# turn numpy arrays into tensors

# difference between numpy arrays and tensors flow :
# TensorFlow can be run on GPU which is faster

import numpy as np

numpy_A = np.arange(1,25, dtype=np.int32)
numpy_A

In [ ]:
A = tf.constant(numpy_A)
A

In [ ]:
A = tf.constant(numpy_A, shape=(2,3,4))
A

In [ ]:
A.ndim

In [ ]:
B = tf.constant(numpy_A)
B

In [ ]:
B.ndim

In [ ]:
C = tf.constant(numpy_A, shape=(3,8))
C

In [ ]:
C.ndim

## **Lesson 21**

In [ ]:
# Getting Informations from tensors


In [57]:
#A.ndim
#tf.size(A)
#tf.size(B)
tf.size(C)

<tf.Tensor: shape=(), dtype=int32, numpy=24>