<a href="https://colab.research.google.com/github/pascalbuchert/Python-AI/blob/main/00_tensorflow_fundamentals_Part3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Matrix Multiplication**
www.matrixmultiplication.xyz


In [1]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [2]:
# matrix multiplication in tensor flow
# create a rank 4 tensor

tensor = tf.zeros(shape=[2,3,4,5])
tensor


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [3]:
a=tf.constant([1,2,3,4,5,6], shape=[2,3])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [4]:
b=tf.constant([7,8,9,10,11,12], shape =[3,2])
b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [5]:
c=tf.matmul(a,b)
c #c= a x b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [6]:
# Matrix multiplication
print(a)
tf.matmul(a,b)
tf.matmul(b,a)


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]], dtype=int32)>

In [7]:
# Tensor definition
tensor=tf.constant([10,7,3,4], shape=[2,2])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [8]:
tensor, tensor


(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>)

In [9]:
tensor * tensor
# Wrong result !!!!

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [10]:
tf.matmul(tensor, tensor)
# Correct Result !!

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [11]:
tensor_a=tf.constant([1,2,5,7,2,1,3,3,3], shape=[3,3])
tensor_a

tensor_b=tf.constant([3,5,6,7,1,8], shape=[3,2])
tensor_b

tensor_a, tensor_b

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [12]:
# tensor_a * tensor_b
# -> ERROR : Incompatible shapes

In [13]:
# tensor multiplication : Use @
tensor_a @ tensor_b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [14]:
#
tf.matmul(tensor_a, tensor_b)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [16]:
# create a tensor (3,2,)
X = tf.constant([[1,2],[3,4,],[5,6]])
Y = tf.constant([[7,8],
                [9,10],
                 [11,12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Matrix multiplication of matrix same shape
# X @ Y
# ERROR: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name:

In [ ]:
# Matrix multiplication of matrix same shape
# tf.matmul(X, Y)
# ERROR: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name:

In [ ]:
# Resource
# https://mathsisfun.com/algebra/matrix-multiplying.html

# There are 2 rules on tensors or matrics for multiplication:
# 1, the inner dimension muss match
# 2, the resulting matrix has the shape of the inner dimension
X, Y

In [ ]:
# Reshape Y
Y_Reshaped = tf.reshape(Y, [2,3])
X, Y, Y_Reshaped,  X @ Y_Reshaped

In [19]:
# Transpose
# do the same a reshape

X, tf.transpose(X), tf.reshape(X, shape=(2,3,))


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [20]:
# Transpose Flips the axis
print ("X:", X), Y, print ("Y:", Y) , print ("Transpose X:", tf.transpose(X)) ,print ("Transpose(X) * Y:", tf.matmul(tf.transpose(X),Y))

X: tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Y: tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
Transpose X: tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)
Transpose(X) * Y: tf.Tensor(
[[ 89  98]
 [116 128]], shape=(2, 2), dtype=int32)


(None,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>,
 None,
 None,
 None)

# Chapter 25 : Matrix multiplication with **Tensor**

In [34]:
# Chapter 25 : Matrix multiplication with Tensor

# create a tensor (3,2,)
X = tf.constant([[1,2],[3,4,],[5,6]])
Y = tf.constant([[7,8],
                [9,10],
                 [11,12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [36]:
#tf.matmul (X,Y)

In [37]:
# change the shape o Y
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [38]:
X, Y, tf.reshape(Y, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>)

In [39]:
# Multiplication
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [201]:
X.shape, tf.reshape(Y, shape=(2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [202]:
tf.matmul (X,tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [203]:
tf.matmul (tf.reshape (X, (2,3,)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [204]:
# Can we do the same with transpose ?

X, tf.transpose (X), tf.reshape(X,(2,3,))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [206]:
X, tf.transpose (X)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>)

### Chapter **26**

In [ ]:
# dot product = matrix multiplication

# tf.matmul()
# tf.tensordot()

# perform the dot product on X and Y reqquires X or Y to be transposed



In [212]:
X,tf.transpose(X), Y


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [213]:
tf.tensordot (tf.transpose(X),Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [215]:
# perform matrix multiplicationbetween X and Y (tansposed)
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [217]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X,tf.reshape(Y,[2,3]))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [221]:
# Check the values of Y, reshape Y and transpose Y
print("Normal Y:")
print(Y, "\n")
print("Reshape Y:")
print (tf.reshape(Y,[2,3]),"\n")
print("Transpose Y:")
print(tf.transpose (Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Reshape Y:
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Transpose Y:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [223]:
X, tf.matmul (X, tf.transpose(Y))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]], dtype=int32)>)

## Chapter **27**

In [229]:
# Change the datatype of a tensor
# default in int32

# create a new FLOAT 32 tensor
B= tf.constant([1.7,7.4])
B.dtype

tf.float32

In [225]:
C=tf.constant([7,10])
C.dtype

tf.int32

In [230]:
# change fromn float 32 to float 16, run 3 times faster in aveage

D=tf.cast(B, dtype=tf.float16)
B,D



(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>)

In [231]:
# change from int32 to float32
E=tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [234]:
E_float16=tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### Chapter 28 : Tensor **Aggregation**

In [236]:
# Aggregation tensor = condensing multiple values to a smaller amount of values

# Get the absolute values
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [238]:
# abs = absolute value
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
# tensor aggregations : Minimum, maximum, mean, sum


In [239]:
import torch

In [240]:
torch_ten = torch.randn(10)
print("This is a Sample torch tensor:", torch_ten)

This is a Sample torch tensor: tensor([-1.0672, -1.1037,  1.6019,  0.7120,  0.7747, -2.1778,  0.7618, -1.2611,
        -0.4126, -1.5251])


In [241]:
print("This is minimum value of Sample tensor:",torch.min(torch_ten))
print("This is maximum value of Sample tensor:",torch.max(torch_ten))

This is minimum value of Sample tensor: tensor(-2.1778)
This is maximum value of Sample tensor: tensor(1.6019)


In [246]:
#import numpy as np

In [260]:
# create random tensor with values between 0 and 100 of size 50
E=tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([89,  7, 23, 51, 98, 76, 41, 31, 24, 99, 94, 89, 90, 29,  4, 45, 78,
       55, 60, 50, 36, 51, 73, 40, 17, 11, 82, 66, 59, 37, 28, 67, 37, 43,
       56, 21, 40, 13, 74, 37, 75, 63, 38, 95, 56, 21, 27, 42, 95,  8])>

In [263]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [265]:
# Minimum, Maximum, mean
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [266]:
# Max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [267]:
# Mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [268]:
# Sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2541>

In [274]:
# Find the variance and standard deviation of E Tensors
import tensorflow_probability as tfp

In [277]:
# Need acces to tensorFlow Probalbility
tfp.stats.variance(E)


<tf.Tensor: shape=(), dtype=int64, numpy=728>

In [289]:
tf.cast (E, dtype=tf.float32) ,  tfp.stats.stddev( tf.cast (E, dtype=tf.float32))

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([89.,  7., 23., 51., 98., 76., 41., 31., 24., 99., 94., 89., 90.,
        29.,  4., 45., 78., 55., 60., 50., 36., 51., 73., 40., 17., 11.,
        82., 66., 59., 37., 28., 67., 37., 43., 56., 21., 40., 13., 74.,
        37., 75., 63., 38., 95., 56., 21., 27., 42., 95.,  8.],
       dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=26.975315>)

In [291]:
# find the variance of a tensor
tf.math.reduce_std(tf.cast (E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=26.975315>