<a href="https://colab.research.google.com/github/pascalbuchert/Python-AI/blob/main/Copy_of_My_Exercises_00_Fudamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **00 TensorFlow Fundamentals Exercises**
1, Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

2, Find the shape, rank and size of the tensors you created in 1.

3, Create two tensors containing random values between 0 and 1 with shape [5, 300].
4, Multiply the two tensors you created in 3 using matrix multiplication.

5, Multiply the two tensors you created in 3 using dot product.

6, Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

7, Find the min and max values of the tensor you created in 6.

8, Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

9, Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

10, One-hot encode the tensor you created in 9.

In [3]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [4]:
import numpy as np
print (np.__version__)

1.25.2


In [5]:
# Creating a scalar
scalar = tf.constant(8)


In [6]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [7]:
vector = tf.constant ([1,2,3])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [8]:
matrix=tf.constant ([[1,2,3],[4,5,6]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [9]:
tensor=tf.constant ([
                      [
                          [1,2,3],
                          [4,5,6],
                      ],
                      [
                          [7,8,9],
                          [10,11,12]
                      ],
                    ])
tensor


<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [10]:
tensor1=tf.constant ([
                      [
                          [1,2,3],
                          [4,5,6],
                          [1,2,3],
                          [1,2,3],
                      ],
                      [
                          [7,8,9],
                          [10,11,12],
                          [1,2,3],
                          [1,2,3],
                      ],
                      [
                          [7,8,9],
                          [10,11,12],
                          [1,2,3],
                          [1,2,3],
                      ],
                    ])
tensor1

<tf.Tensor: shape=(3, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 1,  2,  3],
        [ 1,  2,  3]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 1,  2,  3],
        [ 1,  2,  3]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 1,  2,  3],
        [ 1,  2,  3]]], dtype=int32)>

In [11]:
scalar, vector , matrix , tensor

(<tf.Tensor: shape=(), dtype=int32, numpy=8>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]], dtype=int32)>)

In [12]:
tensor.shape

TensorShape([2, 2, 3])

In [13]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [14]:
tf.size(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [15]:
print ("Rank :", tf.rank(tensor)) , print ("Size :", tf.size(tensor)), print ('Shape :', tensor.shape)

Rank : tf.Tensor(3, shape=(), dtype=int32)
Size : tf.Tensor(12, shape=(), dtype=int32)
Shape : (2, 2, 3)


(None, None, None)

In [40]:
# Finding the shape, rank and size
print(f'The shape of the tensor: {tensor.shape} \n')
print(f'The rank of the tensor: {tf.size(tensor)}')
print(f'The rank of the tensor: {tf.rank(tensor)}')

The shape of the tensor: (2, 2, 3) 

The rank of the tensor: 12
The rank of the tensor: 3


In [43]:
# 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

tensor1=tf.random.uniform(shape=([5,300]), minval=0, maxval=1)
tensor2=tf.random.uniform(shape=(5,300))
tensor3=tf.random.uniform(shape=(5,300),  minval=0, maxval=1, dtype=tf.float16)
tensor1, tensor2, tensor3

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.51422644, 0.78501344, 0.40096712, ..., 0.07534921, 0.5288094 ,
         0.52117836],
        [0.3265512 , 0.11403716, 0.5561334 , ..., 0.11643136, 0.7320765 ,
         0.7860048 ],
        [0.31075191, 0.7672703 , 0.90348005, ..., 0.7603648 , 0.28392506,
         0.6456026 ],
        [0.946419  , 0.9858916 , 0.9947567 , ..., 0.715711  , 0.21062458,
         0.24767852],
        [0.01469648, 0.12517393, 0.5708058 , ..., 0.8697324 , 0.522437  ,
         0.32691395]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.13429701, 0.78589785, 0.11465394, ..., 0.22554135, 0.46752012,
         0.59157455],
        [0.30267227, 0.4598384 , 0.7151743 , ..., 0.21740663, 0.10570741,
         0.20814478],
        [0.05029333, 0.36259043, 0.5195594 , ..., 0.87202513, 0.506392  ,
         0.00363874],
        [0.05174267, 0.4507141 , 0.6124078 , ..., 0.46519303, 0.26456094,
         0.00779128],
        [0.19188

In [33]:
tensor1.shape, tensor2.shape, tensor3.shape

(TensorShape([5, 300]), TensorShape([5, 300]), TensorShape([5, 300]))

In [ ]:
# Multiply the two tensors you created in 3 using matrix multiplication.

In [37]:
# Multiplying
print('Shape before the matrix multiplication')
print(tensor1.shape , '\n')
print(tensor2.shape , '\n')

Shape before the matrix multiplication
(5, 300) 

(5, 300) 



In [44]:
tf.math.multiply (tensor1, tensor2)

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.06905907, 0.6169404 , 0.04597246, ..., 0.01699436, 0.24722904,
        0.30831584],
       [0.09883799, 0.05243866, 0.39773232, ..., 0.02531295, 0.07738591,
        0.1636028 ],
       [0.01562875, 0.2782049 , 0.46941155, ..., 0.6630572 , 0.14377737,
        0.00234918],
       [0.04897025, 0.44435525, 0.6091968 , ..., 0.33294377, 0.05572303,
        0.00192973],
       [0.00281996, 0.11851882, 0.34562725, ..., 0.6647321 , 0.07508186,
        0.30924308]], dtype=float32)>

In [53]:
resultant_vector = tf.linalg.matmul(tensor1 , tf.transpose(tensor2))
print(f'After multiplying the resultant vector is: \n {resultant_vector} \n')

print(f'The resultant vector shape: \n {resultant_vector.shape}')

After multiplying the resultant vector is: 
 [[76.19787  83.58377  76.59679  77.28656  79.81519 ]
 [73.52505  78.65989  74.55926  73.188126 78.668686]
 [73.58214  78.92472  79.27861  75.76319  82.82646 ]
 [74.56005  81.555984 78.05837  73.11509  77.25167 ]
 [69.719215 77.6528   74.55645  70.83353  75.209435]] 

The resultant vector shape: 
 (5, 5)


In [50]:
#5. Multiply the two tensors you created in 3 using dot product.
# Compute the dot product
dot_product = tf.reduce_sum(tf.multiply(tensor1, tensor2))
dot_product.numpy()

382.46094

In [51]:
# Using tensordot
tf.tensordot(tensor1 , tf.transpose(tensor2) , axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[76.19787 , 83.58377 , 76.59679 , 77.28656 , 79.81519 ],
       [73.52505 , 78.65989 , 74.55926 , 73.188126, 78.668686],
       [73.58214 , 78.92472 , 79.27861 , 75.76319 , 82.82646 ],
       [74.56005 , 81.555984, 78.05837 , 73.11509 , 77.25167 ],
       [69.719215, 77.6528  , 74.55645 , 70.83353 , 75.209435]],
      dtype=float32)>

In [59]:
#6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
big_tensor = tf.random.uniform([224,224,3], minval=0, maxval=1)
big_tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.8099226 , 0.2671739 , 0.49362612],
        [0.9933735 , 0.8539411 , 0.7124926 ],
        [0.49007034, 0.7493442 , 0.10653436],
        ...,
        [0.72813666, 0.14077115, 0.548921  ],
        [0.49111462, 0.25185168, 0.0344727 ],
        [0.7054566 , 0.53752446, 0.44388342]],

       [[0.36210394, 0.48879611, 0.08266127],
        [0.30857193, 0.39605117, 0.41951978],
        [0.497777  , 0.25214553, 0.83635783],
        ...,
        [0.16957211, 0.3787241 , 0.89068186],
        [0.9323337 , 0.2966603 , 0.71113074],
        [0.6793971 , 0.93989396, 0.6811974 ]],

       [[0.5758449 , 0.25607204, 0.23790228],
        [0.32451642, 0.7886219 , 0.0236603 ],
        [0.46527267, 0.4049393 , 0.00516796],
        ...,
        [0.43183148, 0.09044838, 0.2596786 ],
        [0.5069891 , 0.6155001 , 0.4077412 ],
        [0.26727366, 0.03793049, 0.9034445 ]],

       ...,

       [[0.8609569 , 0.58088005, 0.58183074],
        [0.33

In [60]:
# Checking the min and max value of our tensor
print(f'Maximum value: {tf.reduce_max(big_tensor)}')
print(f'Minimum value: {tf.reduce_min(big_tensor)}')

Maximum value: 0.9999932050704956
Minimum value: 3.0279159545898438e-05


In [61]:
# Checking the min and max value of our tensor
print('Maximum value: {tf.reduce_max(big_tensor)}')
print('Minimum value: {tf.reduce_min(big_tensor)}')

Maximum value: {tf.reduce_max(big_tensor)}
Minimum value: {tf.reduce_min(big_tensor)}


In [63]:
# Checking the min and max value of our tensor
print('Maximum value: ',tf.reduce_max(big_tensor))
print('Minimum value: ', tf.reduce_min(big_tensor))

Maximum value:  tf.Tensor(0.9999932, shape=(), dtype=float32)
Minimum value:  tf.Tensor(3.027916e-05, shape=(), dtype=float32)


In [64]:
#7. Find the min and max values of the tensor you created in 6.
# Finding the minimum
minimum = tf.math.reduce_min(big_tensor)
print(f'The minimum value is: {minimum}')

The minimum value is: 3.0279159545898438e-05


In [65]:
# Finding the minimum
maximum = tf.math.reduce_max(big_tensor)
print(f'The maximum value is: {maximum}')

The maximum value is: 0.9999932050704956


In [70]:
#  Created a tensor with random values of shape [1, 224, 224, 3]
#  then squeeze it to change the shape to [224, 224, 3].

unsqueezed_tensor=tf.random.uniform([1,224,224,3])
unsqueezed_tensor, unsqueezed_tensor.shape, unsqueezed_tensor.numpy

(<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
 array([[[[0.35118496, 0.01266646, 0.30242097],
          [0.14470696, 0.5305339 , 0.7567191 ],
          [0.721261  , 0.1683687 , 0.5200244 ],
          ...,
          [0.6549908 , 0.8958285 , 0.46285844],
          [0.76270056, 0.17602384, 0.9442265 ],
          [0.3526944 , 0.43091786, 0.05862391]],
 
         [[0.26672828, 0.1355784 , 0.2934003 ],
          [0.75921214, 0.46636415, 0.30123878],
          [0.9824641 , 0.49148953, 0.08356845],
          ...,
          [0.82925963, 0.6720706 , 0.95956945],
          [0.8419291 , 0.7581476 , 0.49147522],
          [0.78068316, 0.04119182, 0.5533539 ]],
 
         [[0.25516307, 0.99788773, 0.523705  ],
          [0.05302119, 0.19380212, 0.5647352 ],
          [0.5686238 , 0.30895495, 0.8203471 ],
          ...,
          [0.05618727, 0.94623077, 0.2846676 ],
          [0.27590954, 0.6071942 , 0.41027665],
          [0.9184736 , 0.73701537, 0.5910864 ]],
 
         ...,
 
       

In [71]:
squeezed_tensor =tf.squeeze(unsqueezed_tensor)
squeezed_tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.35118496, 0.01266646, 0.30242097],
        [0.14470696, 0.5305339 , 0.7567191 ],
        [0.721261  , 0.1683687 , 0.5200244 ],
        ...,
        [0.6549908 , 0.8958285 , 0.46285844],
        [0.76270056, 0.17602384, 0.9442265 ],
        [0.3526944 , 0.43091786, 0.05862391]],

       [[0.26672828, 0.1355784 , 0.2934003 ],
        [0.75921214, 0.46636415, 0.30123878],
        [0.9824641 , 0.49148953, 0.08356845],
        ...,
        [0.82925963, 0.6720706 , 0.95956945],
        [0.8419291 , 0.7581476 , 0.49147522],
        [0.78068316, 0.04119182, 0.5533539 ]],

       [[0.25516307, 0.99788773, 0.523705  ],
        [0.05302119, 0.19380212, 0.5647352 ],
        [0.5686238 , 0.30895495, 0.8203471 ],
        ...,
        [0.05618727, 0.94623077, 0.2846676 ],
        [0.27590954, 0.6071942 , 0.41027665],
        [0.9184736 , 0.73701537, 0.5910864 ]],

       ...,

       [[0.41360736, 0.8447075 , 0.6214646 ],
        [0.24

In [76]:

# Tensor with shape [224 , 224 , 3]
unsqueezed_tensor = tf.random.Generator.from_seed(42)
unsqueezed_tensor = unsqueezed_tensor.normal(shape = (2, 1 , 224 , 224 , 3))

print(f'The shape before squeezing: {unsqueezed_tensor.shape}')


The shape before squeezing: (2, 1, 224, 224, 3)


In [77]:
# And we are squeezing it
squeezed_tensor = tf.squeeze(unsqueezed_tensor)
print(f'The shape after squeezing: {squeezed_tensor.shape}')

The shape after squeezing: (2, 224, 224, 3)


In [89]:
# Create a tensor with shape [10] using your own choice of values,
# then find the index which has the maximum value.

tensor_ten =tf.random.uniform([10], minval=0, maxval=10)
tensor_ten.shape, tensor_ten.numpy

(TensorShape([10]),
 <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([1.1088431 , 0.6041181 , 2.5991285 , 7.1758184 , 7.787819  ,
        7.3056307 , 0.97208023, 1.0907018 , 3.5740185 , 3.3802903 ],
       dtype=float32)>>)

In [90]:
max_value=tf.math.argmax (tensor_ten)
max_value
print(f'The indices where the value is maximum: {max_value}')
print(f'The maximum value was: {tensor_ten[max_value]}')

The indices where the value is maximum: 4
The maximum value was: 7.787818908691406


In [91]:
# 10. One-hot encode the tensor you created in 9.
# Throw's an error since I had floating numbers in my tensor, casting to int solved!
tf.cast(tensor_ten , dtype=tf.int32)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 0, 2, 7, 7, 7, 0, 1, 3, 3], dtype=int32)>

In [93]:
# One hot encoding the tensor of shape 10
tf.one_hot(tf.cast(tensor_ten , dtype=tf.int32) , depth = 10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>