<a href="https://colab.research.google.com/github/pascalbuchert/Python-AI/blob/main/Copy_of_My_Exercises_00_Fudamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **00 TensorFlow Fundamentals Exercises**
1, Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

2, Find the shape, rank and size of the tensors you created in 1.

3, Create two tensors containing random values between 0 and 1 with shape [5, 300].
4, Multiply the two tensors you created in 3 using matrix multiplication.

5, Multiply the two tensors you created in 3 using dot product.

6, Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

7, Find the min and max values of the tensor you created in 6.

8, Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

9, Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

10, One-hot encode the tensor you created in 9.

In [3]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [4]:
import numpy as np
print (np.__version__)

1.25.2


In [5]:
# Creating a scalar
scalar = tf.constant(8)


In [6]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [7]:
vector = tf.constant ([1,2,3])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [8]:
matrix=tf.constant ([[1,2,3],[4,5,6]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [9]:
tensor=tf.constant ([
                      [
                          [1,2,3],
                          [4,5,6],
                      ],
                      [
                          [7,8,9],
                          [10,11,12]
                      ],
                    ])
tensor


<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [10]:
tensor1=tf.constant ([
                      [
                          [1,2,3],
                          [4,5,6],
                          [1,2,3],
                          [1,2,3],
                      ],
                      [
                          [7,8,9],
                          [10,11,12],
                          [1,2,3],
                          [1,2,3],
                      ],
                      [
                          [7,8,9],
                          [10,11,12],
                          [1,2,3],
                          [1,2,3],
                      ],
                    ])
tensor1

<tf.Tensor: shape=(3, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 1,  2,  3],
        [ 1,  2,  3]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 1,  2,  3],
        [ 1,  2,  3]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 1,  2,  3],
        [ 1,  2,  3]]], dtype=int32)>

In [11]:
scalar, vector , matrix , tensor

(<tf.Tensor: shape=(), dtype=int32, numpy=8>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]], dtype=int32)>)

In [12]:
tensor.shape

TensorShape([2, 2, 3])

In [13]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [14]:
tf.size(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [15]:
print ("Rank :", tf.rank(tensor)) , print ("Size :", tf.size(tensor)), print ('Shape :', tensor.shape)

Rank : tf.Tensor(3, shape=(), dtype=int32)
Size : tf.Tensor(12, shape=(), dtype=int32)
Shape : (2, 2, 3)


(None, None, None)

In [17]:
# Finding the shape, rank and size
print(f'The shape of the tensor: {tensor.shape}')
print(f'The rank of the tensor: {tf.size(tensor)}')
print(f'The rank of the tensor: {tf.rank(tensor)}')

The shape of the tensor: (2, 2, 3)
The rank of the tensor: 12
The rank of the tensor: 3


In [31]:
# 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

tensor1=tf.random.uniform(shape=([5,300]), minval=0, maxval=1, dtype=tf.int32)
tensor2=tf.random.uniform(shape=(5,300))
tensor3=tf.random.uniform(shape=(5,300),  minval=0, maxval=1, dtype=tf.float16)
tensor1, tensor2, tensor3

(<tf.Tensor: shape=(5, 300), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[8.0274928e-01, 6.5804112e-01, 7.5157261e-01, ..., 4.1381252e-01,
         9.6413004e-01, 2.7060509e-04],
        [8.6550879e-01, 6.9939101e-01, 1.2856960e-01, ..., 4.3856752e-01,
         8.9914894e-01, 1.9188619e-01],
        [9.1754913e-02, 1.4701545e-01, 1.7523777e-01, ..., 9.6415174e-01,
         2.4209619e-01, 5.5769181e-01],
        [8.7465262e-01, 8.6813962e-01, 9.8211551e-01, ..., 5.3363216e-01,
         8.3900619e-01, 7.3770916e-01],
        [1.7703545e-01, 6.0190618e-01, 7.3130178e-01, ..., 6.5849578e-01,
         7.4140179e-01, 5.5148757e-01]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float16, numpy=
 array([[0.754  , 0.8486 , 0.2686 , ..., 0.586  , 0.0371 , 0.2979 ],
        [0.

In [32]:
tensor1.shape, tensor2.shape, tensor3.shape

(TensorShape([5, 300]), TensorShape([5, 300]), TensorShape([5, 300]))